import { colors, radius, spacing, typography } from '@/constants/theme';
import { initializeDatabase } from '@/database';
import { createCredit, listCreditPayments, listCredits, recordCreditPayment } from '@/database/repositories/credit';
import { createCustomer, CustomerInput, listCustomers } from '@/database/repositories/customers';
import { createProduct, findProductByBarcode as findProductByBarcodeRecord, listProducts, ProductInput, updateProductRecord } from '@/database/repositories/products';
import { completeCheckout, listSales } from '@/database/repositories/sales';
import { getReportSnapshot } from '@/database/repositories/reports';
import { recordStockMovement, StockMovementInput } from '@/database/repositories/stockMovements';
import { createStaff, listUsers, resetStaffCredential, setStaffEnabled, updateStaffName } from '@/database/repositories/users';
import { requestSyncSoon } from '@/services/supabase/trigger';
import { CartItem, CompletedSale, CreditRecord, Customer, PaymentMethod, PaymentRecord, Product, ReportSnapshot, StaffAccount, Transaction } from '@/types';
import { createContext, PropsWithChildren, useCallback, useContext, useEffect, useMemo, useState } from 'react';
import { ActivityIndicator, Pressable, StyleSheet, Text, View } from 'react-native';

type AppState = {
  products: Product[]; cart: CartItem[]; cartCount: number; cartSubtotal: number; customers: Customer[]; credits: CreditRecord[]; payments: PaymentRecord[]; transactions: Transaction[]; staff: StaffAccount[]; reports: ReportSnapshot; selectedCustomerId: string | null; lastSale: CompletedSale | null; heldSales: number;
  addToCart: (productId: string, quantity?: number) => void; setCartQuantity: (productId: string, quantity: number) => void; removeFromCart: (productId: string) => void; clearCart: () => void; holdSale: () => void; selectCustomer: (id: string | null) => void;
  addProduct: (input: ProductInput) => Promise<Product>; updateProduct: (id: string, changes: Partial<ProductInput>) => Promise<void>; findProductByBarcode: (barcode: string) => Promise<Product | null>; adjustStock: (id: string, amount: number, details?: Omit<StockMovementInput, 'productId' | 'amount'>) => Promise<boolean>;
  pendingScannedBarcode: string | null; setPendingScannedBarcode: (barcode: string | null) => void;
  addCustomer: (input: CustomerInput) => Promise<Customer>; addUtang: (customerId: string, input: { description: string; amount: number; dueDate: string; notes?: string; createdBy?: string }) => Promise<CreditRecord>; collectPayment: (customerId: string, amount: number, method: Exclude<PaymentMethod, 'Utang'>, reference?: string, receivedBy?: string) => Promise<void>;
  checkout: (cashierId: string, method: PaymentMethod, cashReceived?: number, reference?: string) => Promise<CompletedSale>;
  addStaff: (name: string, username: string) => Promise<void>; renameStaff: (id: string, name: string) => Promise<void>; toggleStaff: (id: string) => Promise<void>; resetStaffPin: (id: string) => Promise<void>; refreshAll: () => Promise<void>; refreshReports: () => Promise<void>;
};
const AppContext = createContext<AppState | null>(null);

export function AppProvider({ children }: PropsWithChildren) {
  const emptyReports: ReportSnapshot = { sales: { totalSales: 0, totalProfit: 0, transactionCount: 0, averageSale: 0, topProducts: [], byCashier: [] }, inventory: { totalProducts: 0, inventoryValue: 0, lowStock: 0, outOfStock: 0 }, utang: { totalOutstanding: 0, totalCollected: 0, customersWithUtang: 0, overdue: 0 } }; const [products, setProducts] = useState<Product[]>([]); const [cart, setCart] = useState<CartItem[]>([]); const [customers, setCustomers] = useState<Customer[]>([]); const [credits, setCredits] = useState<CreditRecord[]>([]); const [payments, setPayments] = useState<PaymentRecord[]>([]); const [transactions, setTransactions] = useState<Transaction[]>([]); const [staff, setStaff] = useState<StaffAccount[]>([]); const [reports, setReports] = useState<ReportSnapshot>(emptyReports); const [selectedCustomerId, setSelectedCustomerId] = useState<string | null>(null); const [lastSale, setLastSale] = useState<CompletedSale | null>(null); const [heldSales, setHeldSales] = useState(0); const [pendingScannedBarcode, setPendingScannedBarcode] = useState<string | null>(null); const [loading, setLoading] = useState(true); const [databaseFailed, setDatabaseFailed] = useState(false);
  const refreshReports = useCallback(async () => { setReports(await getReportSnapshot()); }, []);
  const refreshAll = useCallback(async () => { const [nextProducts, nextCustomers, nextCredits, nextPayments, nextTransactions, nextStaff, nextReports] = await Promise.all([listProducts(), listCustomers(), listCredits(), listCreditPayments(), listSales(), listUsers(), getReportSnapshot()]); setProducts(nextProducts); setCustomers(nextCustomers); setCredits(nextCredits); setPayments(nextPayments); setTransactions(nextTransactions); setStaff(nextStaff); setReports(nextReports); }, []);
  const startDatabase = useCallback(async () => { try { await initializeDatabase(); await refreshAll(); } catch (error) { console.error('Database initialization failed', error); setDatabaseFailed(true); } finally { setLoading(false); } }, [refreshAll]);
  // SQLite initialization is an external-system synchronization; state updates occur after awaited I/O.
  useEffect(() => { void startDatabase(); }, [startDatabase]);
  const cartCount = cart.reduce((sum, item) => sum + item.quantity, 0); const cartSubtotal = cart.reduce((sum, item) => sum + (products.find((product) => product.id === item.productId)?.price ?? 0) * item.quantity, 0);
  const value = useMemo<AppState>(() => ({ products, cart, cartCount, cartSubtotal, customers, credits, payments, transactions, staff, reports, selectedCustomerId, lastSale, heldSales, pendingScannedBarcode, setPendingScannedBarcode, refreshAll, refreshReports,
    addToCart: (productId, quantity = 1) => setCart((current) => { const product = products.find((item) => item.id === productId); if (!product || product.stock <= 0) return current; return current.some((item) => item.productId === productId) ? current.map((item) => item.productId === productId ? { ...item, quantity: Math.min(product.stock, item.quantity + quantity) } : item) : [...current, { productId, quantity: Math.min(product.stock, quantity) }]; }),
    setCartQuantity: (productId, quantity) => setCart((current) => { const product = products.find((item) => item.id === productId); const safeQuantity = Math.min(product?.stock ?? quantity, quantity); return safeQuantity <= 0 ? current.filter((item) => item.productId !== productId) : current.map((item) => item.productId === productId ? { ...item, quantity: safeQuantity } : item); }), removeFromCart: (productId) => setCart((current) => current.filter((item) => item.productId !== productId)), clearCart: () => { setCart([]); setSelectedCustomerId(null); }, holdSale: () => { if (cart.length) { setHeldSales((count) => count + 1); setCart([]); setSelectedCustomerId(null); } }, selectCustomer: setSelectedCustomerId,
    addProduct: async (input) => { const id = await createProduct(input); const next = await listProducts(); setProducts(next); requestSyncSoon(); const product = next.find((item) => item.id === id); if (!product) throw new Error('Saved product could not be loaded.'); return product; }, updateProduct: async (id, changes) => { await updateProductRecord(id, changes); setProducts(await listProducts()); requestSyncSoon(); }, findProductByBarcode: findProductByBarcodeRecord, adjustStock: async (id, amount, details) => { try { await recordStockMovement({ productId: id, amount, ...details }); setProducts(await listProducts()); requestSyncSoon(); return true; } catch { return false; } },
    addCustomer: async (input) => { const id = await createCustomer(input); const next = await listCustomers(); setCustomers(next); requestSyncSoon(); const customer = next.find((item) => item.id === id); if (!customer) throw new Error('Saved customer could not be loaded.'); return customer; }, addUtang: async (customerId, input) => { const id = await createCredit(customerId, input); const [nextCredits, nextCustomers] = await Promise.all([listCredits(), listCustomers()]); setCredits(nextCredits); setCustomers(nextCustomers); requestSyncSoon(); const credit = nextCredits.find((item) => item.id === id); if (!credit) throw new Error('Saved credit could not be loaded.'); return credit; }, collectPayment: async (customerId, amount, method, reference, receivedBy) => { await recordCreditPayment(customerId, amount, method, reference, receivedBy); const [nextCredits, nextCustomers, nextPayments] = await Promise.all([listCredits(), listCustomers(), listCreditPayments()]); setCredits(nextCredits); setCustomers(nextCustomers); setPayments(nextPayments); requestSyncSoon(); },
    checkout: async (cashierId, method, cashReceived, reference) => { const sale = await completeCheckout({ cart, customerId: selectedCustomerId, cashierId, method, cashReceived, reference }); const [nextProducts, nextCustomers, nextCredits, nextTransactions, nextReports] = await Promise.all([listProducts(), listCustomers(), listCredits(), listSales(), getReportSnapshot()]); setProducts(nextProducts); setCustomers(nextCustomers); setCredits(nextCredits); setTransactions(nextTransactions); setReports(nextReports); setLastSale(sale); setCart([]); setSelectedCustomerId(null); requestSyncSoon(); return sale; },
    addStaff: async (name, username) => { await createStaff(name, username); setStaff(await listUsers()); requestSyncSoon(); }, renameStaff: async (id, name) => { await updateStaffName(id, name); setStaff(await listUsers()); requestSyncSoon(); }, toggleStaff: async (id) => { const account = staff.find((item) => item.id === id); if (!account) return; await setStaffEnabled(id, !account.active); setStaff(await listUsers()); requestSyncSoon(); }, resetStaffPin: async (id) => { await resetStaffCredential(id); requestSyncSoon(); },
  }), [products, cart, cartCount, cartSubtotal, customers, credits, payments, transactions, staff, reports, selectedCustomerId, lastSale, heldSales, pendingScannedBarcode, refreshAll, refreshReports]);
  if (loading) return <View style={styles.loading}><ActivityIndicator size="large" color={colors.primary} /><Text style={styles.loadingTitle}>Opening Sari-sari Store</Text><Text style={styles.loadingText}>Preparing your offline data…</Text></View>;
  if (databaseFailed) return <View style={styles.loading}><Text style={styles.errorTitle}>Unable to open local data</Text><Text style={styles.loadingText}>Your data was not changed. Please restart the app or try again.</Text><Pressable style={styles.retry} onPress={() => { setLoading(true); setDatabaseFailed(false); void startDatabase(); }}><Text style={styles.retryText}>Try Again</Text></Pressable></View>;
  return <AppContext.Provider value={value}>{children}</AppContext.Provider>;
}
export function useAppStore() { const context = useContext(AppContext); if (!context) throw new Error('useAppStore must be used within AppProvider'); return context; }
const styles = StyleSheet.create({ loading: { flex: 1, backgroundColor: colors.background, alignItems: 'center', justifyContent: 'center', gap: spacing.md, padding: spacing.xl }, loadingTitle: { color: colors.text, fontSize: typography.title, fontWeight: typography.bold }, errorTitle: { color: colors.danger, fontSize: typography.title, fontWeight: typography.bold, textAlign: 'center' }, loadingText: { color: colors.textMuted, textAlign: 'center', lineHeight: 21 }, retry: { marginTop: spacing.sm, backgroundColor: colors.primary, paddingHorizontal: spacing.xl, paddingVertical: spacing.md, borderRadius: radius.md }, retryText: { color: colors.white, fontWeight: typography.semibold } });
