import { createThemedStyles, useAppearance } from '@/store/appearance';
import { radius, spacing, typography } from '@/constants/theme';
import { initializeDatabase } from '@/database';
import { listCreditPayments, listCredits, recordCreditPayment } from '@/database/repositories/credit';
import { createCustomer, CustomerInput, listCustomers, updateCustomer as updateCustomerRecord } from '@/database/repositories/customers';
import { createProduct, findProductByBarcode as findProductByBarcodeRecord, isProductImageUriInUse, listProducts, ProductInput, updateProductRecord } from '@/database/repositories/products';
import { deletePendingSale as deletePendingSaleRecord, listPendingSales, loadPendingSaleForResume, savePendingSale } from '@/database/repositories/pendingSales';
import { completeCheckout, listSales } from '@/database/repositories/sales';
import { getReportSnapshot } from '@/database/repositories/reports';
import { refundSale, voidSale } from '@/database/repositories/reversals';
import { recordStockMovement, StockMovementInput } from '@/database/repositories/stockMovements';
import { getOwner } from '@/database/repositories/users';
import { deleteProductImage } from '@/services/productImages';
import { requestSyncSoon } from '@/services/supabase/trigger';
import { CartItem, CompletedSale, CreditRecord, Customer, PaymentMethod, PaymentRecord, PendingSale, Product, ReportSnapshot, Transaction } from '@/types';
import { calculateDiscount } from '@/utils/discount';
import { createContext, PropsWithChildren, useCallback, useContext, useEffect, useMemo, useRef, useState } from 'react';
import { ActivityIndicator, Pressable, Text, View } from 'react-native';

type AppState = {
  products: Product[]; cart: CartItem[]; cartCount: number; cartSubtotal: number; cartDiscount: number; cartTotal: number; customerDiscountApplied: boolean; customers: Customer[]; credits: CreditRecord[]; payments: PaymentRecord[]; transactions: Transaction[]; reports: ReportSnapshot; selectedCustomerId: string | null; utangSaleCustomerId: string | null; lastSale: CompletedSale | null; pendingSales: PendingSale[];
  addToCart: (productId: string, quantity?: number) => void; setCartQuantity: (productId: string, quantity: number) => void; removeFromCart: (productId: string) => void; clearCart: () => void; saveForLater: () => Promise<void>; resumePendingSale: (id: string) => Promise<void>; deletePendingSale: (id: string) => Promise<void>; selectCustomer: (id: string | null) => void;
  addProduct: (input: ProductInput) => Promise<Product>; updateProduct: (id: string, changes: Partial<ProductInput>) => Promise<void>; findProductByBarcode: (barcode: string) => Promise<Product | null>; adjustStock: (id: string, amount: number, details?: Omit<StockMovementInput, 'productId' | 'amount'>) => Promise<boolean>;
  pendingScannedBarcode: string | null; setPendingScannedBarcode: (barcode: string | null) => void;
  addCustomer: (input: CustomerInput) => Promise<Customer>; updateCustomer: (id: string, input: CustomerInput) => Promise<Customer>; setCustomerDiscountApplied: (applied: boolean) => void; collectPayment: (customerId: string, amount: number, method: Exclude<PaymentMethod, 'Utang'>, reference?: string, receivedBy?: string) => Promise<void>;
  beginUtangSale: (customerId: string) => void; cancelUtangSale: () => void;
  checkout: (method: PaymentMethod, cashReceived?: number, reference?: string, dueDate?: string, notes?: string) => Promise<CompletedSale>;
  voidTransaction: (saleId: string, actorId: string, reason: string) => Promise<void>; refundTransaction: (saleId: string, actorId: string, reason: string, method: Exclude<PaymentMethod, 'Utang'>) => Promise<void>;
  refreshAll: () => Promise<void>; refreshReports: () => Promise<void>; resetAfterStoreReset: () => Promise<void>;
};
const AppContext = createContext<AppState | null>(null);
const emptyReports: ReportSnapshot = { sales: { totalSales: 0, todaySales: 0, todayProfit: 0, totalProfit: 0, transactionCount: 0, averageSale: 0, topProducts: [], byCashier: [] }, inventory: { totalProducts: 0, inventoryValue: 0, lowStock: 0, outOfStock: 0 }, utang: { totalOutstanding: 0, totalCollected: 0, customersWithUtang: 0, overdue: 0 } };

export function AppProvider({ children }: PropsWithChildren) {
  const { colors } = useAppearance();
  const styles = useStyles();
  const [products, setProducts] = useState<Product[]>([]); const [cart, setCart] = useState<CartItem[]>([]); const [customers, setCustomers] = useState<Customer[]>([]); const [credits, setCredits] = useState<CreditRecord[]>([]); const [payments, setPayments] = useState<PaymentRecord[]>([]); const [transactions, setTransactions] = useState<Transaction[]>([]); const [reports, setReports] = useState<ReportSnapshot>(emptyReports); const [selectedCustomerId, setSelectedCustomerId] = useState<string | null>(null); const [customerDiscountApplied, setCustomerDiscountApplied] = useState(true); const [utangSaleCustomerId, setUtangSaleCustomerId] = useState<string | null>(null); const [lastSale, setLastSale] = useState<CompletedSale | null>(null); const [pendingSales, setPendingSales] = useState<PendingSale[]>([]); const [pendingScannedBarcode, setPendingScannedBarcode] = useState<string | null>(null); const [loading, setLoading] = useState(true); const [databaseFailed, setDatabaseFailed] = useState(false); const refreshGeneration = useRef(0);
  const refreshReports = useCallback(async () => { const generation = refreshGeneration.current; const nextReports = await getReportSnapshot(); if (generation === refreshGeneration.current) setReports(nextReports); }, []);
  const refreshAll = useCallback(async () => { const generation = refreshGeneration.current; const [nextProducts, nextCustomers, nextCredits, nextPayments, nextTransactions, nextReports, nextPendingSales] = await Promise.all([listProducts(), listCustomers(), listCredits(), listCreditPayments(), listSales(), getReportSnapshot(), listPendingSales()]); if (generation !== refreshGeneration.current) return; setProducts(nextProducts); setCustomers(nextCustomers); setCredits(nextCredits); setPayments(nextPayments); setTransactions(nextTransactions); setReports(nextReports); setPendingSales(nextPendingSales); }, []);
  const resetAfterStoreReset = useCallback(async () => {
    refreshGeneration.current += 1;
    setProducts([]); setCustomers([]); setCredits([]); setPayments([]); setTransactions([]); setPendingSales([]); setReports(emptyReports);
    setCart([]); setSelectedCustomerId(null); setCustomerDiscountApplied(true); setUtangSaleCustomerId(null); setLastSale(null); setPendingScannedBarcode(null);
    await refreshAll();
  }, [refreshAll]);
  const startDatabase = useCallback(async () => { try { await initializeDatabase(); await refreshAll(); } catch (error) { console.error('Database initialization failed', error); setDatabaseFailed(true); } finally { setLoading(false); } }, [refreshAll]);
  // SQLite initialization is an external-system synchronization; state updates occur after awaited I/O.
  useEffect(() => { void startDatabase(); }, [startDatabase]);
  const cartCount = cart.reduce((sum, item) => sum + item.quantity, 0); const cartSubtotal = cart.reduce((sum, item) => sum + (products.find((product) => product.id === item.productId)?.price ?? 0) * item.quantity, 0);
  const selectedCustomer = customers.find((customer) => customer.id === selectedCustomerId);
  const cartPricing = calculateDiscount(cartSubtotal, selectedCustomer?.customerType === 'suki' && customerDiscountApplied ? selectedCustomer.discountType : 'none', selectedCustomer?.discountValue ?? 0);
  const value = useMemo<AppState>(() => ({ products, cart, cartCount, cartSubtotal: cartPricing.subtotal, cartDiscount: cartPricing.discountAmount, cartTotal: cartPricing.finalTotal, customerDiscountApplied, setCustomerDiscountApplied, customers, credits, payments, transactions, reports, selectedCustomerId, utangSaleCustomerId, lastSale, pendingSales, pendingScannedBarcode, setPendingScannedBarcode, refreshAll, refreshReports, resetAfterStoreReset,
    addToCart: (productId, quantity = 1) => setCart((current) => { const product = products.find((item) => item.id === productId); if (!product || product.stock <= 0) return current; return current.some((item) => item.productId === productId) ? current.map((item) => item.productId === productId ? { ...item, quantity: Math.min(product.stock, item.quantity + quantity) } : item) : [...current, { productId, quantity: Math.min(product.stock, quantity) }]; }),
    setCartQuantity: (productId, quantity) => setCart((current) => { const product = products.find((item) => item.id === productId); const safeQuantity = Math.min(product?.stock ?? quantity, quantity); return safeQuantity <= 0 ? current.filter((item) => item.productId !== productId) : current.map((item) => item.productId === productId ? { ...item, quantity: safeQuantity } : item); }), removeFromCart: (productId) => setCart((current) => current.filter((item) => item.productId !== productId)), clearCart: () => { setCart([]); setSelectedCustomerId(null); setCustomerDiscountApplied(true); setUtangSaleCustomerId(null); }, saveForLater: async () => { await savePendingSale(cart, selectedCustomerId, cartPricing.discountAmount); setPendingSales(await listPendingSales()); setCart([]); setSelectedCustomerId(null); setCustomerDiscountApplied(true); setUtangSaleCustomerId(null); }, resumePendingSale: async (id) => { const pending = await loadPendingSaleForResume(id); await deletePendingSaleRecord(id); setCart(pending.items); setSelectedCustomerId(pending.customerId); setCustomerDiscountApplied(pending.discount > 0); setUtangSaleCustomerId(null); setPendingSales(await listPendingSales()); }, deletePendingSale: async (id) => { await deletePendingSaleRecord(id); setPendingSales(await listPendingSales()); }, selectCustomer: (id) => { setSelectedCustomerId(id); setCustomerDiscountApplied(true); },
    addProduct: async (input) => { const id = await createProduct(input); const next = await listProducts(); setProducts(next); requestSyncSoon(); const product = next.find((item) => item.id === id); if (!product) throw new Error('Saved product could not be loaded.'); return product; }, updateProduct: async (id, changes) => { const previousImageUri = await updateProductRecord(id, changes); setProducts(await listProducts()); if (changes.imageUri !== undefined && previousImageUri && previousImageUri !== changes.imageUri) { try { if (!(await isProductImageUriInUse(previousImageUri))) deleteProductImage(previousImageUri); } catch (error) { console.warn('Old product image could not be removed', error); } } requestSyncSoon(); }, findProductByBarcode: findProductByBarcodeRecord, adjustStock: async (id, amount, details) => { try { await recordStockMovement({ productId: id, amount, ...details }); setProducts(await listProducts()); requestSyncSoon(); return true; } catch { return false; } },
    addCustomer: async (input) => { const id = await createCustomer(input); const next = await listCustomers(); setCustomers(next); requestSyncSoon(); const customer = next.find((item) => item.id === id); if (!customer) throw new Error('Saved customer could not be loaded.'); return customer; }, updateCustomer: async (id, input) => { await updateCustomerRecord(id, input); const next = await listCustomers(); setCustomers(next); requestSyncSoon(); const customer = next.find((item) => item.id === id); if (!customer) throw new Error('Updated customer could not be loaded.'); return customer; }, collectPayment: async (customerId, amount, method, reference, receivedBy) => { await recordCreditPayment(customerId, amount, method, reference, receivedBy); const [nextCredits, nextCustomers, nextPayments] = await Promise.all([listCredits(), listCustomers(), listCreditPayments()]); setCredits(nextCredits); setCustomers(nextCustomers); setPayments(nextPayments); requestSyncSoon(); },
    beginUtangSale: (customerId) => { const customer = customers.find((item) => item.id === customerId); if (!customer?.allowUtang) return; setSelectedCustomerId(customerId); setCustomerDiscountApplied(true); setUtangSaleCustomerId(customerId); }, cancelUtangSale: () => { setUtangSaleCustomerId(null); setSelectedCustomerId(null); setCustomerDiscountApplied(true); },
    checkout: async (method, cashReceived, reference, dueDate, notes) => { const owner = await getOwner(); const sale = await completeCheckout({ cart, customerId: selectedCustomerId, cashierId: owner.id, method, cashReceived, reference, dueDate, notes, applyCustomerDiscount: customerDiscountApplied }); const [nextProducts, nextCustomers, nextCredits, nextTransactions, nextReports] = await Promise.all([listProducts(), listCustomers(), listCredits(), listSales(), getReportSnapshot()]); setProducts(nextProducts); setCustomers(nextCustomers); setCredits(nextCredits); setTransactions(nextTransactions); setReports(nextReports); setLastSale(sale); setCart([]); setSelectedCustomerId(null); setCustomerDiscountApplied(true); setUtangSaleCustomerId(null); requestSyncSoon(); return sale; },
    voidTransaction: async (saleId, actorId, reason) => { await voidSale(saleId, actorId, reason); await refreshAll(); requestSyncSoon(); },
    refundTransaction: async (saleId, actorId, reason, method) => { await refundSale(saleId, actorId, reason, method); await refreshAll(); requestSyncSoon(); },
  }), [products, cart, cartCount, cartPricing.subtotal, cartPricing.discountAmount, cartPricing.finalTotal, customerDiscountApplied, customers, credits, payments, transactions, reports, selectedCustomerId, utangSaleCustomerId, lastSale, pendingSales, pendingScannedBarcode, refreshAll, refreshReports, resetAfterStoreReset]);
  if (loading) return <View style={styles.loading}><ActivityIndicator size="large" color={colors.primary} /><Text style={styles.loadingTitle}>Opening Sari-sari Store</Text><Text style={styles.loadingText}>Preparing your offline data…</Text></View>;
  if (databaseFailed) return <View style={styles.loading}><Text style={styles.errorTitle}>Unable to open local data</Text><Text style={styles.loadingText}>Your data was not changed. Please restart the app or try again.</Text><Pressable style={styles.retry} onPress={() => { setLoading(true); setDatabaseFailed(false); void startDatabase(); }}><Text style={styles.retryText}>Try Again</Text></Pressable></View>;
  return <AppContext.Provider value={value}>{children}</AppContext.Provider>;
}
export function useAppStore() { const context = useContext(AppContext); if (!context) throw new Error('useAppStore must be used within AppProvider'); return context; }
const useStyles = createThemedStyles((colors) => ({ loading: { flex: 1, backgroundColor: colors.background, alignItems: 'center', justifyContent: 'center', gap: spacing.md, padding: spacing.xl }, loadingTitle: { color: colors.text, fontSize: typography.title, fontWeight: typography.bold }, errorTitle: { color: colors.danger, fontSize: typography.title, fontWeight: typography.bold, textAlign: 'center' }, loadingText: { color: colors.textMuted, textAlign: 'center', lineHeight: 21 }, retry: { marginTop: spacing.sm, backgroundColor: colors.primary, paddingHorizontal: spacing.xl, paddingVertical: spacing.md, borderRadius: radius.md }, retryText: { color: colors.primaryText, fontWeight: typography.semibold } }));
