import { getDatabase } from '@/database';
import { ReportSnapshot } from '@/types';

export async function getReportSnapshot(): Promise<ReportSnapshot> {
  const db = await getDatabase();
  const sales = await db.getFirstAsync<{ total_sales: number; transaction_count: number }>(`SELECT COALESCE(SUM(total), 0) AS total_sales, COUNT(*) AS transaction_count FROM sales WHERE status = 'completed' AND deleted_at IS NULL`);
  const profit = await db.getFirstAsync<{ total_profit: number }>(`SELECT COALESCE(SUM((si.unit_price - si.cost_price) * si.quantity), 0) AS total_profit FROM sale_items si JOIN sales s ON s.id = si.sale_id WHERE s.status = 'completed' AND s.deleted_at IS NULL AND si.deleted_at IS NULL`);
  const topProducts = await db.getAllAsync<{ name: string; quantity: number; total: number }>(`SELECT si.product_name_snapshot AS name, SUM(si.quantity) AS quantity, SUM(si.subtotal) AS total FROM sale_items si JOIN sales s ON s.id = si.sale_id WHERE s.status = 'completed' AND s.deleted_at IS NULL AND si.deleted_at IS NULL GROUP BY si.product_name_snapshot ORDER BY quantity DESC LIMIT 5`);
  const byCashier = await db.getAllAsync<{ name: string; total: number; count: number }>(`SELECT u.name, COALESCE(SUM(CASE WHEN s.status = 'completed' AND s.deleted_at IS NULL THEN s.total ELSE 0 END), 0) AS total, COUNT(CASE WHEN s.status = 'completed' AND s.deleted_at IS NULL THEN 1 END) AS count FROM users u LEFT JOIN sales s ON s.cashier_id = u.id WHERE u.deleted_at IS NULL GROUP BY u.id ORDER BY CASE u.role WHEN 'admin' THEN 0 ELSE 1 END, u.name`);
  const inventory = await db.getFirstAsync<{ total_products: number; inventory_value: number; low_stock: number; out_of_stock: number }>(`SELECT COUNT(*) AS total_products, COALESCE(SUM(cost_price * cached_stock), 0) AS inventory_value, SUM(CASE WHEN cached_stock > 0 AND cached_stock <= low_stock_threshold THEN 1 ELSE 0 END) AS low_stock, SUM(CASE WHEN cached_stock = 0 THEN 1 ELSE 0 END) AS out_of_stock FROM products WHERE is_active = 1 AND deleted_at IS NULL`);
  const utang = await db.getFirstAsync<{ outstanding: number; collected: number; customers_count: number; overdue: number }>(`SELECT MAX(0, COALESCE((SELECT SUM(amount) FROM credit_transactions WHERE deleted_at IS NULL), 0) - COALESCE((SELECT SUM(amount) FROM credit_payments WHERE deleted_at IS NULL), 0)) AS outstanding, COALESCE((SELECT SUM(amount) FROM credit_payments WHERE deleted_at IS NULL), 0) AS collected, (SELECT COUNT(*) FROM customers c WHERE c.deleted_at IS NULL AND COALESCE((SELECT SUM(amount) FROM credit_transactions WHERE customer_id = c.id AND deleted_at IS NULL), 0) > COALESCE((SELECT SUM(amount) FROM credit_payments WHERE customer_id = c.id AND deleted_at IS NULL), 0)) AS customers_count, (SELECT COUNT(*) FROM credit_transactions WHERE status = 'Overdue' AND deleted_at IS NULL) AS overdue`);
  const totalSales = sales?.total_sales ?? 0; const transactionCount = sales?.transaction_count ?? 0;
  return { sales: { totalSales, totalProfit: profit?.total_profit ?? 0, transactionCount, averageSale: transactionCount ? totalSales / transactionCount : 0, topProducts, byCashier }, inventory: { totalProducts: inventory?.total_products ?? 0, inventoryValue: inventory?.inventory_value ?? 0, lowStock: inventory?.low_stock ?? 0, outOfStock: inventory?.out_of_stock ?? 0 }, utang: { totalOutstanding: utang?.outstanding ?? 0, totalCollected: utang?.collected ?? 0, customersWithUtang: utang?.customers_count ?? 0, overdue: utang?.overdue ?? 0 } };
}
