import { getDatabase, runInTransaction } from '@/database';
import { createId, nowIso } from '@/database/ids';
import { queueSync } from '@/database/syncQueue';
import { CartItem, CompletedSale, PaymentMethod, Transaction } from '@/types';

type SaleRow = { id: string; transaction_number: string; created_at: string; total: number; cashier: string; status: 'completed' | 'held' | 'voided' };

export async function listSales(): Promise<Transaction[]> {
  const db = await getDatabase();
  const rows = await db.getAllAsync<SaleRow>('SELECT s.id, s.transaction_number, s.created_at, s.total, u.name AS cashier, s.status FROM sales s JOIN users u ON u.id = s.cashier_id WHERE s.deleted_at IS NULL ORDER BY s.created_at DESC');
  return rows.filter((row) => row.status !== 'voided').map((row) => ({ saleId: row.id, id: row.transaction_number, time: new Date(row.created_at).toLocaleString('en-PH', { dateStyle: 'medium', timeStyle: 'short' }), amount: row.total, cashier: row.cashier, status: row.status === 'held' ? 'Held' : 'Completed' }));
}
export async function completeCheckout(input: { cart: CartItem[]; customerId: string | null; cashierId: string; method: PaymentMethod; cashReceived?: number; reference?: string }): Promise<CompletedSale> { return runInTransaction(async (db) => { if (!input.cart.length) throw new Error('Cart is empty.'); const now = nowIso(); const productRows = await Promise.all(input.cart.map((item) => db.getFirstAsync<{ id: string; name: string; selling_price: number; cost_price: number; cached_stock: number }>('SELECT id, name, selling_price, cost_price, cached_stock FROM products WHERE id = ? AND is_active = 1', item.productId))); let total = 0; for (let index = 0; index < input.cart.length; index += 1) { const item = input.cart[index]; const product = productRows[index]; if (!product) throw new Error('A cart product is unavailable.'); if (item.quantity <= 0 || product.cached_stock < item.quantity) throw new Error(`Insufficient stock for ${product.name}.`); total += product.selling_price * item.quantity; }
    const customer = input.customerId ? await db.getFirstAsync<{ id: string; full_name: string; credit_limit: number; balance: number }>(`SELECT c.id, c.full_name, c.credit_limit, MAX(0, COALESCE((SELECT SUM(amount) FROM credit_transactions WHERE customer_id = c.id), 0) - COALESCE((SELECT SUM(amount) FROM credit_payments WHERE customer_id = c.id), 0)) AS balance FROM customers c WHERE c.id = ?`, input.customerId) : null; if (input.method === 'Utang' && (!customer || customer.balance + total > customer.credit_limit)) throw new Error('A registered customer with sufficient credit is required.'); if (input.method === 'Cash' && (input.cashReceived ?? 0) < total) throw new Error('Cash received is insufficient.'); const cashier = await db.getFirstAsync<{ name: string }>('SELECT name FROM users WHERE id = ? AND status = ?', input.cashierId, 'active'); if (!cashier) throw new Error('Cashier account is unavailable.');
    const saleId = createId(); const transactionNumber = `#TXN${Date.now()}${Math.floor(Math.random() * 90 + 10)}`; const change = input.method === 'Cash' ? (input.cashReceived ?? 0) - total : null; await db.runAsync('INSERT INTO sales (id, transaction_number, customer_id, cashier_id, payment_method, subtotal, discount, total, cash_received, change_amount, reference_number, status, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, 0, ?, ?, ?, ?, ?, ?, ?)', saleId, transactionNumber, customer?.id ?? null, input.cashierId, input.method, total, total, input.method === 'Cash' ? input.cashReceived ?? null : null, change, input.reference || null, 'completed', now, now);
    for (let index = 0; index < input.cart.length; index += 1) { const item = input.cart[index]; const product = productRows[index]!; const itemId = createId(); const movementId = createId(); const subtotal = product.selling_price * item.quantity; await db.runAsync('INSERT INTO sale_items (id, sale_id, product_id, product_name_snapshot, quantity, unit_price, cost_price, subtotal, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)', itemId, saleId, product.id, product.name, item.quantity, product.selling_price, product.cost_price, subtotal, now, now); await db.runAsync('INSERT INTO stock_movements (id, product_id, type, quantity, reason, reference, notes, created_by, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)', movementId, product.id, 'sale', item.quantity, 'POS sale', transactionNumber, null, input.cashierId, now, now); const stockUpdate = await db.runAsync('UPDATE products SET cached_stock = cached_stock - ? WHERE id = ? AND cached_stock >= ?', item.quantity, product.id, item.quantity); if (stockUpdate.changes !== 1) throw new Error(`Stock changed while checking out ${product.name}.`); await queueSync(db, 'sale_items', itemId, 'create', { id: itemId, saleId, productId: product.id, quantity: item.quantity, unitPrice: product.selling_price, subtotal }); await queueSync(db, 'stock_movements', movementId, 'create', { id: movementId, productId: product.id, type: 'sale', quantity: item.quantity }); }
    if (input.method === 'Utang' && customer) { const creditId = createId(); await db.runAsync('INSERT INTO credit_transactions (id, customer_id, sale_id, amount, due_date, description, notes, status, created_by, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)', creditId, customer.id, saleId, total, null, 'POS purchase', transactionNumber, 'Due', input.cashierId, now, now); await queueSync(db, 'credit_transactions', creditId, 'create', { id: creditId, customerId: customer.id, saleId, amount: total }); }
    await queueSync(db, 'sales', saleId, 'create', { id: saleId, transactionNumber, customerId: customer?.id ?? null, cashierId: input.cashierId, paymentMethod: input.method, total, status: 'completed' }); return { saleId, id: transactionNumber, date: new Date(now).toLocaleString('en-PH', { dateStyle: 'medium', timeStyle: 'short' }), cashier: cashier.name, customer: customer?.full_name ?? 'Walk-in Customer', paymentMethod: input.method, total, cashReceived: input.method === 'Cash' ? input.cashReceived : undefined, change: change ?? undefined }; }); }
