import { getDatabase, runInTransaction } from '@/database';

export const syncEntityTypes = ['users', 'categories', 'products', 'stock_movements', 'customers', 'sales', 'sale_items', 'credit_transactions', 'credit_payments', 'settings'] as const;
export type SyncEntityType = (typeof syncEntityTypes)[number];
export type RemoteRecord = Record<string, unknown>;
const localOnlySetting = (key: string) => key.startsWith('sync_') || key === 'development_seeded';

export async function getLocalEntityIds(entityType: SyncEntityType) { const db = await getDatabase(); const key = entityType === 'settings' ? 'key' : 'id'; const rows = await db.getAllAsync<{ value: string }>(`SELECT ${key} AS value FROM ${entityType}`); return rows.map((row) => row.value).filter((value) => entityType !== 'settings' || !localOnlySetting(value)); }

export async function getLocalCloudRecord(entityType: SyncEntityType, entityId: string, deviceId: string): Promise<RemoteRecord | null> {
  const db = await getDatabase(); let row: RemoteRecord | null = null;
  switch (entityType) {
    case 'users': row = await db.getFirstAsync<RemoteRecord>('SELECT id, name, username, role, status, created_at, updated_at, deleted_at FROM users WHERE id = ?', entityId); break;
    case 'categories': row = await db.getFirstAsync<RemoteRecord>('SELECT id, name, created_at, updated_at, deleted_at FROM categories WHERE id = ?', entityId); break;
    case 'products': row = await db.getFirstAsync<RemoteRecord>('SELECT id, name, category_id, selling_price, cost_price, barcode, low_stock_threshold, description, image_uri, is_active, created_at, updated_at, deleted_at FROM products WHERE id = ?', entityId); break;
    case 'stock_movements': row = await db.getFirstAsync<RemoteRecord>('SELECT id, product_id, type, quantity, reason, reference, notes, created_by, created_at, COALESCE(updated_at, created_at) AS updated_at, deleted_at FROM stock_movements WHERE id = ?', entityId); break;
    case 'customers': row = await db.getFirstAsync<RemoteRecord>('SELECT id, full_name, phone, address, credit_limit, created_at, updated_at, deleted_at FROM customers WHERE id = ?', entityId); break;
    case 'sales': row = await db.getFirstAsync<RemoteRecord>('SELECT id, transaction_number, customer_id, cashier_id, payment_method, subtotal, discount, total, cash_received, change_amount, reference_number, status, created_at, COALESCE(updated_at, created_at) AS updated_at, deleted_at FROM sales WHERE id = ?', entityId); break;
    case 'sale_items': row = await db.getFirstAsync<RemoteRecord>('SELECT id, sale_id, product_id, product_name_snapshot, quantity, unit_price, cost_price, subtotal, created_at, COALESCE(updated_at, created_at) AS updated_at, deleted_at FROM sale_items WHERE id = ?', entityId); break;
    case 'credit_transactions': row = await db.getFirstAsync<RemoteRecord>('SELECT id, customer_id, sale_id, amount, due_date, description, notes, status, created_by, created_at, updated_at, deleted_at FROM credit_transactions WHERE id = ?', entityId); break;
    case 'credit_payments': row = await db.getFirstAsync<RemoteRecord>('SELECT id, credit_transaction_id, customer_id, amount, payment_method, reference, notes, received_by, created_at, COALESCE(updated_at, created_at) AS updated_at, deleted_at FROM credit_payments WHERE id = ?', entityId); break;
    case 'settings': if (!localOnlySetting(entityId)) row = await db.getFirstAsync<RemoteRecord>('SELECT key, value, updated_at, deleted_at FROM settings WHERE key = ?', entityId); break;
  }
  return row ? { ...row, origin_device_id: deviceId } : null;
}

const text = (row: RemoteRecord, key: string, fallback = '') => typeof row[key] === 'string' ? row[key] as string : fallback;
const nullableText = (row: RemoteRecord, key: string) => typeof row[key] === 'string' ? row[key] as string : null;
const number = (row: RemoteRecord, key: string, fallback = 0) => typeof row[key] === 'number' ? row[key] as number : fallback;

export async function applyRemoteRecords(entityType: SyncEntityType, records: RemoteRecord[]) {
  if (!records.length) return;
  await runInTransaction(async (db) => {
    for (const row of records) {
      const id = text(row, entityType === 'settings' ? 'key' : 'id'); if (!id) continue;
      const createdAt = text(row, 'created_at', text(row, 'updated_at', new Date().toISOString())); const updatedAt = text(row, 'updated_at', createdAt); const deletedAt = nullableText(row, 'deleted_at'); const origin = nullableText(row, 'origin_device_id');
      switch (entityType) {
        case 'users': await db.runAsync(`INSERT INTO users (id, name, username, password_hash, role, status, created_at, updated_at, deleted_at, origin_device_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?) ON CONFLICT(id) DO UPDATE SET name=excluded.name, username=excluded.username, role=excluded.role, status=CASE WHEN excluded.deleted_at IS NULL THEN excluded.status ELSE 'disabled' END, updated_at=excluded.updated_at, deleted_at=excluded.deleted_at, origin_device_id=excluded.origin_device_id WHERE excluded.updated_at > users.updated_at`, id, text(row, 'name'), text(row, 'username'), 'remote-credential-requires-local-reset', text(row, 'role', 'staff'), deletedAt ? 'disabled' : text(row, 'status', 'active'), createdAt, updatedAt, deletedAt, origin); break;
        case 'categories': await db.runAsync(`INSERT INTO categories (id, name, created_at, updated_at, deleted_at, origin_device_id) VALUES (?, ?, ?, ?, ?, ?) ON CONFLICT(id) DO UPDATE SET name=excluded.name, updated_at=excluded.updated_at, deleted_at=excluded.deleted_at, origin_device_id=excluded.origin_device_id WHERE excluded.updated_at > categories.updated_at`, id, text(row, 'name'), createdAt, updatedAt, deletedAt, origin); break;
        case 'products': await db.runAsync(`INSERT INTO products (id, name, category_id, selling_price, cost_price, barcode, low_stock_threshold, description, image_uri, cached_stock, is_active, created_at, updated_at, deleted_at, origin_device_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, 0, ?, ?, ?, ?, ?) ON CONFLICT(id) DO UPDATE SET name=excluded.name, category_id=excluded.category_id, selling_price=excluded.selling_price, cost_price=excluded.cost_price, barcode=excluded.barcode, low_stock_threshold=excluded.low_stock_threshold, description=excluded.description, image_uri=excluded.image_uri, is_active=excluded.is_active, updated_at=excluded.updated_at, deleted_at=excluded.deleted_at, origin_device_id=excluded.origin_device_id WHERE excluded.updated_at > products.updated_at`, id, text(row, 'name'), nullableText(row, 'category_id'), number(row, 'selling_price'), number(row, 'cost_price'), nullableText(row, 'barcode'), number(row, 'low_stock_threshold'), nullableText(row, 'description'), nullableText(row, 'image_uri'), deletedAt ? 0 : number(row, 'is_active', 1), createdAt, updatedAt, deletedAt, origin); break;
        case 'stock_movements': await db.runAsync('INSERT OR IGNORE INTO stock_movements (id, product_id, type, quantity, reason, reference, notes, created_by, created_at, updated_at, deleted_at, origin_device_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)', id, text(row, 'product_id'), text(row, 'type'), number(row, 'quantity'), nullableText(row, 'reason'), nullableText(row, 'reference'), nullableText(row, 'notes'), nullableText(row, 'created_by'), createdAt, updatedAt, deletedAt, origin); break;
        case 'customers': await db.runAsync(`INSERT INTO customers (id, full_name, phone, address, credit_limit, created_at, updated_at, deleted_at, origin_device_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?) ON CONFLICT(id) DO UPDATE SET full_name=excluded.full_name, phone=excluded.phone, address=excluded.address, credit_limit=excluded.credit_limit, updated_at=excluded.updated_at, deleted_at=excluded.deleted_at, origin_device_id=excluded.origin_device_id WHERE excluded.updated_at > customers.updated_at`, id, text(row, 'full_name'), text(row, 'phone'), nullableText(row, 'address'), number(row, 'credit_limit'), createdAt, updatedAt, deletedAt, origin); break;
        case 'sales': await db.runAsync('INSERT OR IGNORE INTO sales (id, transaction_number, customer_id, cashier_id, payment_method, subtotal, discount, total, cash_received, change_amount, reference_number, status, created_at, updated_at, deleted_at, origin_device_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)', id, text(row, 'transaction_number'), nullableText(row, 'customer_id'), text(row, 'cashier_id'), text(row, 'payment_method'), number(row, 'subtotal'), number(row, 'discount'), number(row, 'total'), typeof row.cash_received === 'number' ? row.cash_received : null, typeof row.change_amount === 'number' ? row.change_amount : null, nullableText(row, 'reference_number'), text(row, 'status', 'completed'), createdAt, updatedAt, deletedAt, origin); break;
        case 'sale_items': await db.runAsync('INSERT OR IGNORE INTO sale_items (id, sale_id, product_id, product_name_snapshot, quantity, unit_price, cost_price, subtotal, created_at, updated_at, deleted_at, origin_device_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)', id, text(row, 'sale_id'), text(row, 'product_id'), text(row, 'product_name_snapshot'), number(row, 'quantity'), number(row, 'unit_price'), number(row, 'cost_price'), number(row, 'subtotal'), createdAt, updatedAt, deletedAt, origin); break;
        case 'credit_transactions': await db.runAsync(`INSERT INTO credit_transactions (id, customer_id, sale_id, amount, due_date, description, notes, status, created_by, created_at, updated_at, deleted_at, origin_device_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) ON CONFLICT(id) DO UPDATE SET status=excluded.status, updated_at=excluded.updated_at, deleted_at=excluded.deleted_at, origin_device_id=excluded.origin_device_id WHERE excluded.updated_at > credit_transactions.updated_at`, id, text(row, 'customer_id'), nullableText(row, 'sale_id'), number(row, 'amount'), nullableText(row, 'due_date'), nullableText(row, 'description'), nullableText(row, 'notes'), text(row, 'status', 'Due'), nullableText(row, 'created_by'), createdAt, updatedAt, deletedAt, origin); break;
        case 'credit_payments': await db.runAsync('INSERT OR IGNORE INTO credit_payments (id, credit_transaction_id, customer_id, amount, payment_method, reference, notes, received_by, created_at, updated_at, deleted_at, origin_device_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)', id, nullableText(row, 'credit_transaction_id'), text(row, 'customer_id'), number(row, 'amount'), text(row, 'payment_method'), nullableText(row, 'reference'), nullableText(row, 'notes'), nullableText(row, 'received_by'), createdAt, updatedAt, deletedAt, origin); break;
        case 'settings': if (!localOnlySetting(id)) await db.runAsync(`INSERT INTO settings (key, value, updated_at, deleted_at, origin_device_id) VALUES (?, ?, ?, ?, ?) ON CONFLICT(key) DO UPDATE SET value=excluded.value, updated_at=excluded.updated_at, deleted_at=excluded.deleted_at, origin_device_id=excluded.origin_device_id WHERE excluded.updated_at > settings.updated_at`, id, text(row, 'value'), updatedAt, deletedAt, origin); break;
      }
    }
  });
}

export async function recomputeCachedStock() { const db = await getDatabase(); await db.runAsync(`UPDATE products SET cached_stock = MAX(0, COALESCE((SELECT SUM(CASE WHEN sm.type = 'stock_in' THEN sm.quantity ELSE -sm.quantity END) FROM stock_movements sm WHERE sm.product_id = products.id AND sm.deleted_at IS NULL), 0))`); }

export async function clearDevelopmentSeedData() { await runInTransaction(async (db) => { const now = new Date().toISOString(); await db.runAsync("DELETE FROM sale_items WHERE sale_id IN (SELECT id FROM sales WHERE reference_number = 'SEED')"); await db.runAsync("DELETE FROM sales WHERE reference_number = 'SEED'"); await db.runAsync("DELETE FROM credit_payments WHERE id LIKE 'seed-payment-%'"); await db.runAsync("DELETE FROM credit_transactions WHERE id LIKE 'seed-credit-%'"); await db.runAsync("DELETE FROM stock_movements WHERE id LIKE 'seed-stock-%'"); await db.runAsync("UPDATE products SET barcode = NULL, deleted_at = ?, updated_at = '1970-01-01T00:00:00.000Z' WHERE id LIKE 'seed-product-%'", now); await db.runAsync("UPDATE categories SET name = '[sample removed] ' || id, deleted_at = ?, updated_at = '1970-01-01T00:00:00.000Z' WHERE id LIKE 'seed-category-%'", now); await db.runAsync("UPDATE customers SET deleted_at = ?, updated_at = '1970-01-01T00:00:00.000Z' WHERE id LIKE 'seed-customer-%'", now); await db.runAsync("UPDATE users SET updated_at = '1970-01-01T00:00:00.000Z' WHERE id LIKE 'seed-%'"); await db.runAsync("DELETE FROM settings WHERE key = 'store_name'"); await db.runAsync("DELETE FROM sync_queue WHERE entity_id LIKE 'seed-%'"); await db.runAsync("UPDATE settings SET value = '0', updated_at = ? WHERE key = 'development_seeded'", now); }); }
