import { createThemedStyles, useAppearance } from '@/store/appearance';
import { FilterChips } from '@/components/FilterChips';
import { FormField } from '@/components/FormField';
import { ProductImage } from '@/components/ProductImage';
import { DateField } from '@/components/DateField';
import { PrimaryButton, ScreenContainer, SectionTitle, SecondaryButton } from '@/components/ui';
import { radius, spacing, typography } from '@/constants/theme';
import { useKeyboardAwareForm } from '@/hooks/useKeyboardAwareForm';
import { defaultPaymentMethods, getPaymentMethodSettings } from '@/services/appSettings';
import { useAppStore } from '@/store/app';
import { useAuth } from '@/store/auth';
import { PaymentMethod } from '@/types';
import { peso } from '@/utils/format';
import { isValidNewDueDate } from '@/utils/date';
import { discountLabel } from '@/utils/discount';
import { Ionicons } from '@expo/vector-icons';
import { router, useFocusEffect } from 'expo-router';
import { useCallback, useState } from 'react';
import { Alert, Pressable, Switch, Text, View } from 'react-native';

const allMethods: PaymentMethod[] = ['Cash', 'GCash', 'Maya', 'Utang'];

export default function CartScreen() {
  const { colors } = useAppearance();
  const styles = useStyles();
  const { cart, products, cartSubtotal, cartDiscount, cartTotal, customerDiscountApplied, setCustomerDiscountApplied, selectedCustomerId, utangSaleCustomerId, customers, setCartQuantity, removeFromCart, selectCustomer, saveForLater, checkout, cancelUtangSale } = useAppStore();
  const { user } = useAuth(); const keyboardForm = useKeyboardAwareForm<'cash' | 'reference' | 'notes'>();
  const [method, setMethod] = useState<PaymentMethod>(utangSaleCustomerId ? 'Utang' : 'Cash'); const [enabledMethods, setEnabledMethods] = useState<PaymentMethod[]>(allMethods); const [cash, setCash] = useState(''); const [reference, setReference] = useState(''); const [dueDate, setDueDate] = useState(''); const [notes, setNotes] = useState(''); const [processing, setProcessing] = useState(false); const [savingLater, setSavingLater] = useState(false);
  useFocusEffect(useCallback(() => { let active = true; void getPaymentMethodSettings().then((settings) => { if (!active) return; const enabled = allMethods.filter((item) => settings[item]); const configured = enabled.length ? enabled : allMethods.filter((item) => defaultPaymentMethods[item]); const safe = utangSaleCustomerId && !configured.includes('Utang') ? [...configured, 'Utang' as const] : configured; setEnabledMethods(safe); setMethod((current) => utangSaleCustomerId ? 'Utang' : safe.includes(current) ? current : safe[0]); }); return () => { active = false; }; }, [utangSaleCustomerId]));
  const customer = customers.find((item) => item.id === selectedCustomerId); const cashValue = Number(cash) || 0; const creditOkay = !!customer?.allowUtang && cartTotal > 0 && cartTotal <= customer.remainingCredit; const dueDateValid = isValidNewDueDate(dueDate); const canCheckout = cart.length > 0 && !!user && (method !== 'Cash' || cashValue >= cartTotal) && (method !== 'Utang' || (creditOkay && dueDateValid));
  const changeMethod = (value: string) => { const next = value as PaymentMethod; setMethod(next); if (utangSaleCustomerId && next !== 'Utang') cancelUtangSale(); };
  const complete = async () => { if (!user || processing) return; setProcessing(true); const customerId = selectedCustomerId; try { const sale = await checkout(method, cashValue, reference, method === 'Utang' ? dueDate : undefined, method === 'Utang' ? notes : undefined); router.replace({ pathname: '/payment-success', params: { saleId: sale.saleId, customerId: customerId ?? undefined } }); } catch (error) { Alert.alert('Checkout failed', error instanceof Error ? error.message : 'The sale was not saved and your cart is unchanged. Check stock and payment details, then try again.'); } finally { setProcessing(false); } };
  const confirmSaveForLater = () => { if (savingLater) return; Alert.alert('Save this cart for later?', 'The items and selected customer will be saved in Pending Sales. Inventory will not be deducted.', [{ text: 'Cancel', style: 'cancel' }, { text: 'Save for Later', onPress: () => void (async () => { setSavingLater(true); try { await saveForLater(); Alert.alert('Saved for later', 'The cart is available in Pending Sales.'); router.replace('/(tabs)/pos'); } catch (error) { Alert.alert('Cart not saved', error instanceof Error ? error.message : 'Please try again.'); } finally { setSavingLater(false); } })() }]); };
  if (!cart.length) return <ScreenContainer style={styles.empty}><Ionicons name="cart-outline" size={72} color={colors.textMuted} /><Text style={styles.emptyTitle}>Your cart is empty</Text><Text style={styles.muted}>Add a product from the POS or barcode scanner.</Text><PrimaryButton title="Browse Products" onPress={() => router.replace('/(tabs)/pos')} /></ScreenContainer>;
  return <ScreenContainer {...keyboardForm.screenProps}><SectionTitle title={`${cart.reduce((sum, item) => sum + item.quantity, 0)} items`} />{cart.map((item) => { const product = products.find((candidate) => candidate.id === item.productId); if (!product) return null; return <View key={product.id} style={styles.row}><ProductImage uri={product.imageUri} fallback={product.icon} size={42} /><View style={styles.flex}><Text style={styles.name}>{product.name}</Text><Text style={styles.price}>{peso(product.price)}</Text></View><View style={styles.quantity}><Pressable onPress={() => setCartQuantity(product.id, item.quantity - 1)}><Ionicons name="remove" color={colors.primary} /></Pressable><Text style={styles.quantityText}>{item.quantity}</Text><Pressable onPress={() => setCartQuantity(product.id, Math.min(product.stock, item.quantity + 1))}><Ionicons name="add" color={colors.primary} /></Pressable></View><Text style={styles.total}>{peso(product.price * item.quantity)}</Text><Pressable accessibilityLabel={`Remove ${product.name}`} onPress={() => removeFromCart(product.id)}><Ionicons name="trash-outline" size={18} color={colors.danger} /></Pressable></View>; })}
    <View style={styles.customer}><Ionicons name="person-outline" size={20} color={colors.primary} /><View style={styles.flex}><Text style={styles.customerLabel}>Customer</Text><Text style={styles.customerName}>{customer?.name ?? 'Walk-in Customer'}</Text>{customer ? <Text style={styles.customerMeta}>{customer.customerType === 'suki' ? 'Suki' : 'Regular'} · {customer.allowUtang ? `Utang allowed · ${peso(customer.remainingCredit)} remaining` : 'Utang not allowed'}</Text> : null}</View>{customer ? <Pressable onPress={() => utangSaleCustomerId ? cancelUtangSale() : selectCustomer(null)}><Text style={styles.clear}>Clear</Text></Pressable> : null}<Pressable onPress={() => router.push({ pathname: '/customers', params: { select: method === 'Utang' ? 'cart-utang' : 'cart' } })}><Text style={styles.change}>{customer ? 'Change Customer' : 'Choose Customer'}</Text></Pressable></View>
    {customer?.customerType === 'suki' && customer.discountType !== 'none' && customer.discountValue > 0 ? <View style={styles.discountToggle}><View style={styles.flex}><Text style={styles.customerName}>Apply Suki Discount</Text><Text style={styles.customerMeta}>{discountLabel(customer.discountType, customer.discountValue, peso)}</Text></View><Switch value={customerDiscountApplied} onValueChange={setCustomerDiscountApplied} trackColor={{ false: colors.border, true: colors.primarySoft }} thumbColor={customerDiscountApplied ? colors.primary : colors.textMuted} /></View> : null}
    <SectionTitle title="Payment Method" /><FilterChips items={enabledMethods} active={method} onChange={changeMethod} />
    {method === 'Cash' ? <><FormField {...keyboardForm.fieldProps('cash')} label="Cash Received" placeholder="₱0.00" keyboardType="decimal-pad" value={cash} onChangeText={setCash} /><View style={styles.changeBox}><Text style={styles.muted}>Change</Text><Text style={[styles.changeValue, cashValue < cartTotal && styles.dangerText]}>{cashValue >= cartTotal ? peso(cashValue - cartTotal) : 'Insufficient cash'}</Text></View></> : null}
    {method === 'GCash' || method === 'Maya' ? <><FormField {...keyboardForm.fieldProps('reference')} label={`${method} Reference (Optional)`} placeholder="Enter transaction reference" value={reference} onChangeText={setReference} /><View style={styles.confirm}><Ionicons name="checkmark-circle-outline" color={colors.success} size={20} /><Text style={styles.confirmText}>Confirm the customer has completed the {method} transfer.</Text></View></> : null}
    {method === 'Utang' ? <><DateField label="Due Date *" value={dueDate} onChange={setDueDate} error={dueDate && !dueDateValid ? 'Select a valid due date.' : undefined} /><FormField {...keyboardForm.fieldProps('notes')} label="Notes" placeholder="Optional notes for this Utang" multiline value={notes} onChangeText={setNotes} /></> : null}
    {method === 'Utang' && !customer ? <View style={styles.warning}><Ionicons name="alert-circle-outline" color={colors.warning} size={20} /><Text style={styles.warningText}>Walk-in customers cannot use Utang. Choose an eligible customer.</Text></View> : null}{method === 'Utang' && customer && !customer.allowUtang ? <View style={styles.warning}><Ionicons name="alert-circle-outline" color={colors.warning} size={20} /><Text style={styles.warningText}>This customer is not allowed to use Utang. Choose another customer.</Text></View> : null}{method === 'Utang' && customer?.allowUtang && !creditOkay ? <View style={styles.warning}><Ionicons name="alert-circle-outline" color={colors.warning} size={20} /><Text style={styles.warningText}>{cartTotal <= 0 ? 'A fully discounted sale does not need Utang.' : `Customer has only ${peso(customer.remainingCredit)} remaining credit.`}</Text></View> : null}
    <View style={styles.summary}><Text style={styles.line}>Subtotal <Text style={styles.strong}>{peso(cartSubtotal)}</Text></Text>{cartDiscount > 0 && customer ? <Text style={styles.line}>{discountLabel(customer.discountType, customer.discountValue, peso)} <Text style={styles.discountAmount}>−{peso(cartDiscount)}</Text></Text> : null}<Text style={styles.grand}>Total Amount <Text>{peso(cartTotal)}</Text></Text></View><View style={styles.buttons}><SecondaryButton title="Save for Later" icon="bookmark-outline" onPress={confirmSaveForLater} style={styles.flex} /><PrimaryButton title="Checkout" icon="card-outline" onPress={() => void complete()} loading={processing} disabled={!canCheckout || savingLater} style={styles.flex} /></View>{!canCheckout ? <Text style={styles.disabledHelp}>Complete the required payment details to enable checkout.</Text> : null}
  </ScreenContainer>;
}
const useStyles = createThemedStyles((colors) => ({ flex: { flex: 1 }, row: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm, backgroundColor: colors.surface, padding: spacing.md, borderRadius: radius.md }, name: { color: colors.text, fontWeight: typography.semibold, fontSize: typography.bodySmall }, price: { color: colors.textMuted, fontSize: typography.caption }, quantity: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm, borderWidth: 1, borderColor: colors.border, borderRadius: radius.pill, paddingHorizontal: spacing.sm, height: 30 }, quantityText: { color: colors.text }, total: { color: colors.text, fontWeight: typography.bold, fontSize: typography.bodySmall }, customer: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm, backgroundColor: colors.surface, padding: spacing.md, borderRadius: radius.md }, customerLabel: { color: colors.textMuted, fontSize: typography.caption }, customerName: { color: colors.text, fontWeight: typography.semibold }, customerMeta: { color: colors.textMuted, fontSize: typography.caption, marginTop: 2 }, change: { color: colors.primary, fontSize: typography.caption, fontWeight: typography.semibold }, clear: { color: colors.danger, fontSize: typography.caption }, discountToggle: { flexDirection: 'row', alignItems: 'center', gap: spacing.md, backgroundColor: colors.primarySoft, padding: spacing.md, borderRadius: radius.md }, summary: { gap: spacing.md, padding: spacing.lg, backgroundColor: colors.surface, borderRadius: radius.lg }, line: { color: colors.textMuted }, strong: { color: colors.text, fontWeight: typography.semibold }, discountAmount: { color: colors.success, fontWeight: typography.bold }, grand: { color: colors.text, fontWeight: typography.bold, fontSize: typography.subtitle }, buttons: { flexDirection: 'row', gap: spacing.sm }, changeBox: { flexDirection: 'row', justifyContent: 'space-between', padding: spacing.md, backgroundColor: colors.successSoft, borderRadius: radius.md }, changeValue: { color: colors.success, fontWeight: typography.bold }, dangerText: { color: colors.danger }, dueError: { color: colors.danger, fontSize: typography.caption }, muted: { color: colors.textMuted, textAlign: 'center' }, warning: { flexDirection: 'row', gap: spacing.sm, padding: spacing.md, backgroundColor: colors.warningSoft, borderRadius: radius.md }, warningText: { flex: 1, color: colors.warning, fontSize: typography.bodySmall }, confirm: { flexDirection: 'row', gap: spacing.sm, padding: spacing.md, backgroundColor: colors.successSoft, borderRadius: radius.md }, confirmText: { flex: 1, color: colors.success, fontSize: typography.bodySmall }, disabledHelp: { textAlign: 'center', color: colors.textMuted, fontSize: typography.caption }, empty: { justifyContent: 'center', alignItems: 'center' }, emptyTitle: { color: colors.text, fontSize: typography.title, fontWeight: typography.bold } }));
