import { createThemedStyles, useAppearance } from '@/store/appearance';
import { Card, PrimaryButton, ScreenContainer, SecondaryButton, StatusBadge } from '@/components/ui';
import { radius, spacing, typography } from '@/constants/theme';
import { bluetoothPrinterConnection, BluetoothPrinterError, connectBluetoothPrinter, disconnectBluetoothPrinter, isBluetoothPrinterModuleAvailable, listPairedPrinters, printBluetoothTest } from '@/services/bluetoothPrinter';
import { forgetSelectedPrinter, getPrinterSettings, PaperWidth, PrinterSettings, saveSelectedPrinter, setPrinterAutoCut, setPrinterAutoPrint, setPrinterPaperWidth } from '@/services/printerSettings';
import type { BluetoothPrinterDevice } from '../../modules/bluetooth-escpos';
import { Ionicons } from '@expo/vector-icons';
import { useFocusEffect } from 'expo-router';
import { useCallback, useState } from 'react';
import { Alert, Pressable, Switch, Text, View } from 'react-native';

type ConnectionState = 'Not configured' | 'Disconnected' | 'Connecting' | 'Connected' | 'Permission required' | 'Printer unavailable';
const emptySettings: PrinterSettings = { selectedId: null, selectedName: null, paperWidth: '58mm', autoCut: true, autoPrint: false };

export default function PrinterSetup() {
  const { colors } = useAppearance();
  const styles = useStyles();
  const [settings, setSettings] = useState(emptySettings); const [devices, setDevices] = useState<BluetoothPrinterDevice[]>([]); const [status, setStatus] = useState<ConnectionState>('Not configured'); const [working, setWorking] = useState<string | null>(null);
  const available = isBluetoothPrinterModuleAvailable();
  const refreshState = useCallback(async () => { const next = await getPrinterSettings(); setSettings(next); const connection = bluetoothPrinterConnection(); setStatus(!next.selectedId ? 'Not configured' : connection.connected && connection.address === next.selectedId ? 'Connected' : 'Disconnected'); }, []);
  useFocusEffect(useCallback(() => { void refreshState(); }, [refreshState]));
  const showError = (error: unknown) => { const message = error instanceof Error ? error.message : 'Please try again.'; setStatus(error instanceof BluetoothPrinterError && error.code === 'PERMISSION' ? 'Permission required' : 'Printer unavailable'); Alert.alert('Bluetooth printer', message); };
  const find = async () => { setWorking('find'); try { const found = await listPairedPrinters(); setDevices(found); if (!found.length) Alert.alert('No paired printers', 'Pair the thermal printer in Android Bluetooth settings, then return and refresh this list.'); } catch (error) { showError(error); } finally { setWorking(null); } };
  const select = async (device: BluetoothPrinterDevice) => { await saveSelectedPrinter(device.address, device.name); setSettings((current) => ({ ...current, selectedId: device.address, selectedName: device.name })); setStatus('Disconnected'); };
  const connect = async () => { if (!settings.selectedId) return; setWorking('connect'); setStatus('Connecting'); try { await connectBluetoothPrinter(settings.selectedId); setStatus('Connected'); } catch (error) { showError(error); } finally { setWorking(null); } };
  const disconnect = async () => { setWorking('disconnect'); try { await disconnectBluetoothPrinter(); setStatus(settings.selectedId ? 'Disconnected' : 'Not configured'); } catch (error) { showError(error); } finally { setWorking(null); } };
  const test = async () => { setWorking('test'); try { await printBluetoothTest(); setStatus('Connected'); Alert.alert('Test sent', 'The printer test was sent successfully.'); } catch (error) { showError(error); } finally { setWorking(null); } };
  const forget = () => Alert.alert('Forget printer?', 'This removes the selected printer from this phone only.', [{ text: 'Cancel', style: 'cancel' }, { text: 'Forget', style: 'destructive', onPress: () => void (async () => { try { await disconnectBluetoothPrinter(); } catch { /* already disconnected */ } await forgetSelectedPrinter(); setSettings((current) => ({ ...current, selectedId: null, selectedName: null })); setStatus('Not configured'); })() }]);
  const updatePaper = async (paperWidth: PaperWidth) => { setSettings((current) => ({ ...current, paperWidth })); await setPrinterPaperWidth(paperWidth); };
  return <ScreenContainer><Card style={styles.statusCard}><View style={styles.printerIcon}><Ionicons name="print-outline" size={28} color={colors.primary} /></View><View style={{ flex: 1 }}><Text style={styles.title}>{settings.selectedName || 'No printer selected'}</Text><Text style={styles.address}>{settings.selectedId || 'Choose a paired Bluetooth printer below'}</Text></View><StatusBadge label={status} tone={status === 'Connected' ? 'success' : status === 'Printer unavailable' || status === 'Permission required' ? 'danger' : 'warning'} /></Card>
    {!available ? <View style={styles.notice}><Ionicons name="information-circle-outline" size={22} color={colors.info} /><Text style={styles.noticeText}>Direct Bluetooth printing is unavailable in Expo Go. Use an Android development or standalone build; all other app features remain available.</Text></View> : null}
    <View style={styles.section}><Text style={styles.heading}>Paper width</Text><View style={styles.options}>{(['58mm', '80mm'] as PaperWidth[]).map((width) => <Pressable key={width} onPress={() => void updatePaper(width)} style={[styles.option, settings.paperWidth === width && styles.optionActive]}><Text style={[styles.optionText, settings.paperWidth === width && styles.optionTextActive]}>{width}</Text></Pressable>)}</View></View>
    <SettingSwitch label="Auto cut" description="Send the standard ESC/POS cut command after printing." value={settings.autoCut} onValueChange={(value) => { setSettings((current) => ({ ...current, autoCut: value })); void setPrinterAutoCut(value); }} />
    <SettingSwitch label="Auto-print after sale" description="Default off. Printing failure never changes a completed sale." value={settings.autoPrint} onValueChange={(value) => { setSettings((current) => ({ ...current, autoPrint: value })); void setPrinterAutoPrint(value); }} />
    <PrimaryButton title={working === 'find' ? 'Checking Paired Devices…' : 'Refresh Paired Printers'} icon="bluetooth-outline" loading={working === 'find'} disabled={!available} onPress={() => void find()} />
    {devices.length ? <View style={styles.deviceList}><Text style={styles.heading}>Paired devices</Text><Text style={styles.help}>Only devices already paired in Android Bluetooth settings are shown.</Text>{devices.map((device) => <Pressable key={device.address} onPress={() => void select(device)} style={[styles.device, settings.selectedId === device.address && styles.deviceSelected]}><Ionicons name="print-outline" size={20} color={colors.primary} /><View style={{ flex: 1 }}><Text style={styles.deviceName}>{device.name}</Text><Text style={styles.address}>{device.address} · Paired</Text></View>{settings.selectedId === device.address ? <Ionicons name="checkmark-circle" size={22} color={colors.success} /> : null}</Pressable>)}</View> : null}
    <View style={styles.actions}>{status === 'Connected' ? <SecondaryButton title="Disconnect" onPress={() => void disconnect()} style={{ flex: 1 }} /> : <PrimaryButton title={working === 'connect' ? 'Connecting…' : 'Connect'} loading={working === 'connect'} disabled={!available || !settings.selectedId} onPress={() => void connect()} style={{ flex: 1 }} />}<SecondaryButton title="Test Print" icon="print-outline" onPress={() => void test()} style={{ flex: 1 }} /></View>
    {settings.selectedId ? <Pressable onPress={forget} style={styles.forget}><Text style={styles.forgetText}>Forget Printer</Text></Pressable> : null}
  </ScreenContainer>;
}

function SettingSwitch({ label, description, value, onValueChange }: { label: string; description: string; value: boolean; onValueChange: (value: boolean) => void }) {
  const { colors } = useAppearance();
  const styles = useStyles(); return <View style={styles.switchRow}><View style={{ flex: 1 }}><Text style={styles.switchLabel}>{label}</Text><Text style={styles.help}>{description}</Text></View><Switch value={value} onValueChange={onValueChange} trackColor={{ false: colors.border, true: colors.primarySoft }} thumbColor={value ? colors.primary : colors.textMuted} /></View>; }
const useStyles = createThemedStyles((colors) => ({ statusCard: { flexDirection: 'row', alignItems: 'center', gap: spacing.md }, printerIcon: { width: 52, height: 52, borderRadius: radius.md, backgroundColor: colors.primarySoft, alignItems: 'center', justifyContent: 'center' }, title: { color: colors.text, fontSize: typography.subtitle, fontWeight: typography.bold }, address: { color: colors.textMuted, fontSize: typography.caption, marginTop: spacing.xs }, notice: { flexDirection: 'row', gap: spacing.sm, padding: spacing.md, borderRadius: radius.md, backgroundColor: colors.infoSoft, borderWidth: 1, borderColor: colors.infoBorder }, noticeText: { flex: 1, color: colors.info, fontSize: typography.bodySmall, lineHeight: 19 }, section: { gap: spacing.sm }, heading: { color: colors.text, fontSize: typography.subtitle, fontWeight: typography.bold }, options: { flexDirection: 'row', gap: spacing.sm }, option: { flex: 1, minHeight: 46, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surface, borderRadius: radius.md }, optionActive: { backgroundColor: colors.primary, borderColor: colors.primary }, optionText: { color: colors.text, fontWeight: typography.semibold }, optionTextActive: { color: colors.white }, switchRow: { flexDirection: 'row', alignItems: 'center', gap: spacing.md, padding: spacing.md, backgroundColor: colors.surface, borderRadius: radius.md }, switchLabel: { color: colors.text, fontWeight: typography.semibold }, help: { color: colors.textMuted, fontSize: typography.caption, lineHeight: 17, marginTop: spacing.xs }, deviceList: { gap: spacing.sm }, device: { flexDirection: 'row', alignItems: 'center', gap: spacing.md, padding: spacing.md, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surface, borderRadius: radius.md }, deviceSelected: { borderColor: colors.success, backgroundColor: colors.successSoft }, deviceName: { color: colors.text, fontWeight: typography.semibold }, actions: { flexDirection: 'row', gap: spacing.sm }, forget: { minHeight: 46, alignItems: 'center', justifyContent: 'center' }, forgetText: { color: colors.danger, fontWeight: typography.semibold } }));
