import { createThemedStyles } from '@/store/appearance';
import { FilterChips } from '@/components/FilterChips';
import { AppHeader, Card, ScreenContainer, SectionTitle, StatCard } from '@/components/ui';
import { radius, spacing, typography } from '@/constants/theme';
import { useAppStore } from '@/store/app';
import { peso } from '@/utils/format';
import { useFocusEffect } from 'expo-router';
import { useCallback, useState } from 'react';
import { Text, View } from 'react-native';
const bars = [30, 48, 66, 55, 78, 64, 92];
export default function ReportsScreen() {  const styles = useStyles();
  const { products, reports, refreshReports } = useAppStore(); const [tab, setTab] = useState('Sales'); const [range, setRange] = useState('This Week');
  useFocusEffect(useCallback(() => { void refreshReports(); }, [refreshReports]));
  return <ScreenContainer><AppHeader title="Reports" subtitle="Business performance at a glance" /><FilterChips items={['Sales', 'Inventory', 'Utang']} active={tab} onChange={setTab} /><FilterChips items={['Today', 'This Week', 'This Month', 'Custom']} active={range} onChange={setRange} />
    {tab === 'Sales' ? <><View style={styles.stats}><StatCard label="Gross Sales" value={peso(reports.sales.grossSales ?? reports.sales.totalSales)} /><StatCard label="Voided Sales" value={peso(reports.sales.voidedSales ?? 0)} tone="red" /><StatCard label="Refunds" value={peso(reports.sales.refunds ?? 0)} tone="orange" /><StatCard label="Net Sales" value={peso(reports.sales.netSales ?? reports.sales.totalSales)} tone="green" /><StatCard label="Completed" value={String(reports.sales.transactionCount)} /><StatCard label="Voided" value={String(reports.sales.voidedCount ?? 0)} tone="red" /><StatCard label="Refunded" value={String(reports.sales.refundedCount ?? 0)} tone="orange" /><StatCard label="Total Profit" value={peso(reports.sales.totalProfit)} tone="green" /></View><Card><SectionTitle title="Sales trend" /><View style={styles.chart}>{bars.map((height, index) => <View key={index} style={styles.track}><View style={[styles.bar, { height }]} /></View>)}</View></Card><Card><SectionTitle title="Top Products" />{reports.sales.topProducts.map((product) => <ReportRow key={product.name} label={product.name} value={`${product.quantity} sold · ${peso(product.total)}`} />)}</Card></> : null}
    {tab === 'Inventory' ? <><View style={styles.stats}><StatCard label="Total Products" value={String(reports.inventory.totalProducts)} /><StatCard label="Inventory Value" value={peso(reports.inventory.inventoryValue)} tone="green" /><StatCard label="Low Stock" value={String(reports.inventory.lowStock)} tone="orange" /><StatCard label="Out of Stock" value={String(reports.inventory.outOfStock)} tone="red" /></View><Card><SectionTitle title="Inventory health" /><ReportRow label="Healthy Stock" value={`${products.filter((p) => p.stock > p.lowStockThreshold).length} products`} /><ReportRow label="Needs Attention" value={`${reports.inventory.lowStock + reports.inventory.outOfStock} products`} /></Card></> : null}
    {tab === 'Utang' ? <><View style={styles.stats}><StatCard label="Total Outstanding" value={peso(reports.utang.totalOutstanding)} tone="orange" /><StatCard label="Total Collected" value={peso(reports.utang.totalCollected)} tone="green" /><StatCard label="Customers with Utang" value={String(reports.utang.customersWithUtang)} /><StatCard label="Overdue" value={String(reports.utang.overdue)} tone="red" /></View><Card><SectionTitle title="Collection summary" /><ReportRow label="Collection Rate" value={`${Math.round((reports.utang.totalCollected / Math.max(1, reports.utang.totalCollected + reports.utang.totalOutstanding)) * 100)}%`} /><ReportRow label="Average Balance" value={peso(reports.utang.totalOutstanding / Math.max(1, reports.utang.customersWithUtang))} /></Card></> : null}
  </ScreenContainer>;
}
function ReportRow({ label, value }: { label: string; value: string }) {  const styles = useStyles(); return <View style={styles.row}><Text style={styles.rowLabel}>{label}</Text><Text style={styles.rowValue}>{value}</Text></View>; }
const useStyles = createThemedStyles((colors) => ({ stats: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between', gap: spacing.md }, chart: { height: 125, flexDirection: 'row', gap: spacing.sm, alignItems: 'flex-end', marginTop: spacing.xl, borderBottomWidth: 1, borderBottomColor: colors.border }, track: { flex: 1, height: 105, justifyContent: 'flex-end' }, bar: { width: '100%', borderTopLeftRadius: radius.sm, borderTopRightRadius: radius.sm, backgroundColor: colors.primary }, row: { flexDirection: 'row', justifyContent: 'space-between', paddingVertical: spacing.md, borderBottomWidth: 1, borderBottomColor: colors.border }, rowLabel: { color: colors.text, fontSize: typography.bodySmall }, rowValue: { color: colors.primary, fontWeight: typography.semibold, fontSize: typography.bodySmall }, cashier: { gap: spacing.xs, paddingVertical: spacing.md, borderBottomWidth: 1, borderBottomColor: colors.border }, cashierDetail: { color: colors.textMuted, fontSize: typography.caption } }));
